### ISSUE TITLE
transactionCompleted and transactionNotCompleted not working

### ISSUE THREAD

**Issue by Henry-246** [popekabu/pay_with_paystack#12]

**Comment by popekabu** [comment]
Please share your process and codes

**Comment by Henry-246** [comment]
It is just print statement. I also tried navigating to a new screen but both didn't work

**Comment by Henry-246** [comment]
> Please share your process and codes
It is just print statement. I also tried navigating to a new screen but both didn't work

**Comment by popekabu** [comment]
I just released an update that addresses the issue
