### ISSUE TITLE
Stuck on payemt page

### ISSUE THREAD

**Issue by greencodder** [popekabu/pay_with_paystack#17]
Hi everyone, 

It seems the initialized payment and webView runs, but no response is not gotten from the  "snapshot".  I tried printing in onNavigationRequest and _checkTransactionStatusSuccessful but it seemed  "_checkTransactionStatusSuccessful"  is never called because it doesn't print anything placed there.  I however noticed this in the debug console window.

"sendCancelIfRunning: isInProgress=falsecallback=ImeCallback=ImeOnBackInvokedCallback@236984737 Callback=android.window.IOnBackInvokedCallback$Stub$Proxy@f1e1952"

**Comment by popekabu** [comment]
Hmmm.. Any findings @greencodder

**Comment by greencodder** [comment]
Still nothing....I had to try inappwebview and I could read when success message is rendered and navigate to a verification page, then call the verify transaction API to verify transaction using the reference code before proceeding but I am having a hard time listening to "Cancel Payment" event.  do I need any system permission enabled? @popekabu

**Comment by popekabu** [comment]
@greencodder Sorry for the late response. I would like to know if you were able to use it or what your final resolutions are?

**Comment by ejioforaustine** [comment]
Hello, 
Anyone manage to pass these? 

its stuck-on payment page doesnt execute any function after payment. not cancellation

**Comment by ejioforaustine** [comment]
Hello, 
Anyone manage to pass these? 

its stuck on payment page doesnt execute any function after payment. not cancellation

**Comment by chuksugwuh** [comment]
Same issue. transactionCompleted is never called.

**Comment by Makuochukwu225** [comment]
@popekabu try the inappwebview onroutechange  callback you can try matching the url since successful payment url is different from failed one

**Comment by popekabu** [comment]
To be honest. I will like to add you as a contributor if you don’t mind so
that you can give it a try. If the results are good i will upload a new
version and mention you as part of the contributors in my readme.

Thank you

**Comment by Makuochukwu225** [comment]
Alright then
________________________________

**Comment by popekabu** [comment]
Thank you Sir
