### ISSUE TITLE
Problem with credentials

### ISSUE THREAD

**Issue by Samson11** [popekabu/pay_with_paystack#2]
When i add my live secret key i get exception : Problem with Paystack Credentials

**Comment by popekabu** [comment]
Are you running the latest version of the plugin? Check your pubspec.yaml, should be version 1.0.1, Thank you!

**Comment by FergyKay** [comment]
Running into same issue 

![Simulator Screen Shot - iPhone 12 mini - 2022-11-09 at 07 00 27](https://user-images.githubusercontent.com/39402738/200761181-d2cdbab1-f2e0-4ec3-96ac-7d51da9822c7.png)

**Comment by popekabu** [comment]
Its an issue from paystack. Try again later if youre sure your paystack secret key is correc

**Comment by FergyKay** [comment]
I have triple checked my credentials. I see you throw an exception of "problem with credentials" on any status code aside 200. How about the actual error code is returned for easy debugging?

**Comment by popekabu** [comment]
Plugin works but i will output the error out as youve suggested, expect an update latest by noon 1200GMT
![Screen Shot 2022-11-09 at 7 12 33 AM](https://user-images.githubusercontent.com/26738997/200763428-cacd4452-b388-4048-99fe-41e00a68d0dd.png)

**Comment by FergyKay** [comment]
Okay. Still debugging. Thanks a tonne, Mann!

**Comment by popekabu** [comment]
Mind you, reference number cannot be repeated

**Comment by FergyKay** [comment]
Yes I understand, it's not being repeated. Having the actual status code will provide some clarity and direction. Will be on standby for updated plugin

**Comment by popekabu** [comment]
No worries, am on it

**Comment by popekabu** [comment]
Done, expect an update anytime soon

**Comment by popekabu** [comment]
Hope @Samson11 this update helps you fix your bugs now and in the future. Thank you.

**Comment by popekabu** [comment]
v1.02 is ready!!  https://pub.dev/packages/pay_with_paystack/versions/1.0.2

**Comment by FergyKay** [comment]
🎊

Managed to debug to see API throwing errors as reference was longer than permitted length. v1.0.2 will really help with debugging. This can be closed now.
