### ISSUE TITLE
Transaction Amount Mismatch Issue

### ISSUE THREAD

**Issue by ZAINBASHARATALI** [popekabu/pay_with_paystack#20]
The amount entered and amount transaction on paystack payments screens is mismatched. 3500 entered becomes 35, 1509 becomes 15.09

This issue is shown in the video as well which you attached as demo, like you entered 20000 but it became 200 on paystack payments screen. Please try to fix this issue as soon as possible.
Thanks

**Comment by Williamtobs** [comment]
Multiply the amount by 100 to get the right amount on payment screen.

**Comment by ZAINBASHARATALI** [comment]
Thanks my friend, i check and found that multiplying by 100 is a
requirement.
Thank you so much for your response.

**Comment by popekabu** [comment]
Thank you @Williamtobs for explaining to him. In the docs for amount in your IDE, I explained it 

```
/// Amount you want to charge the user. Add extra two zeros after typing the amount
    required String amount,
```

Sorry @ZAINBASHARATALI for the delay, I have been inactive for sometime. I am open to anyone looking forward to helping make this plugin more.

Cheers
