### ISSUE TITLE
In test mode, the Amount entered is reduced

### ISSUE THREAD

**Issue by TechnoTron100** [popekabu/pay_with_paystack#24]
For instance, when a user enters 6000 as an amount, the amount charged is 60. I haven't tested in production mode yet. So, I don't know if this is only the case for production mode

**Comment by popekabu** [comment]
Yes, it's the same. Simply multiply whatever amount the user enters by 100
to give them the amount.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by TechnoTron100** [comment]
Thank you for the feedback. Another issue I am facing is after a successful
transaction or failure, it does not close the transaction webview. The user
has to press back.

**Comment by popekabu** [comment]
Hello, Please check out the new version of the package and please ensure
you have set up your callback as part of the parameters. Also be sure its
the same on your paystack dashboard. It should work all things being equal
