### ISSUE TITLE
TextField on Focus Exception

### ISSUE THREAD

**Issue by manAlpha** [popekabu/pay_with_paystack#25]
It works fine, the reference uuid is okay and all until I press the TextField to enter something, then it automatically re-route to the error page with the message duplicated transaction reference even though the reference was unique and not a duplicate. This happens with both MoMo and Card.

Could it be because I haven't set up a callbackUrl in my dashboard yet or something else?

**Comment by popekabu** [comment]
I will look into it after work today. Callback url shouldn’t be the reason
though.

Thanks

**Comment by popekabu** [comment]
Sorry. Allow me to ask. When you say textfield. Is it a flutter widget or a
text box after the paystack screen shows for you to enter your card or momo
details

**Comment by manAlpha** [comment]
The text box after Paystack screen loads where you supposed to enter Momo number, account number, cvv or expiray date. When any one of these get a focus, then this exception happens.

I even changed some of your code to narrow down the cause of the problem and the whole 'build' Widget recall/rebuild whenever there is a focus on any of the listed above TextField (space to enter info).

**Comment by popekabu** [comment]
I personally think its an issue with paystack but will do some
investigations on it more

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
