### ISSUE TITLE
Cancel Button

### ISSUE THREAD

**Issue by Perimac** [popekabu/pay_with_paystack#3]
I tried navigating to another screen on transaction failed but it didn't work. The cancel button on the payment form is not working can you check please.

When onClick of the cancel button does it trigger the transactionNotCompleted function?  If not please check.

**Comment by popekabu** [comment]
Please use the close on the appbar instead.

**Comment by Perimac** [comment]
Please can i use the package for subscription payment?

**Comment by popekabu** [comment]
No, sorry. Will have to do that in the future.
