### ISSUE TITLE
Dupplicate Transaction Reference

### ISSUE THREAD

**Issue by FullStack1106** [popekabu/pay_with_paystack#4]
![Screenshot_1668955971](https://user-images.githubusercontent.com/117177084/202910518-3b9b39d5-b4ac-4f8b-a250-ffb48e626b42.png)

I used UUid to get reference.
so it is unique.
I think this module send request multiple times with same reference.
please let me know how can I fix this issue.
Thank you.

**Comment by popekabu** [comment]
You cant use UUId because it is a static id, reference Id cannot be used more than once. Rather use a random generated alhpanumeric sequence of string or use DateTime

**Comment by FullStack1106** [comment]
Same issue even I use your code.
![image](https://user-images.githubusercontent.com/117177084/202910780-b541c41b-0676-48ce-add6-3f2b71cf3ae3.png)
this is when start transaction.
after 1 second.
![image](https://user-images.githubusercontent.com/117177084/202910801-ae9b061e-618e-42ac-9135-4fd3b076c2b1.png)

**Comment by popekabu** [comment]
this should work. Please check to be sure the app is actually being installed and ran afresh

**Comment by popekabu** [comment]
I would like to close this issue since I haven't heard from @FullStack1106
