### ISSUE TITLE
duplicate transaction reference 

### ISSUE THREAD

**Issue by devkumi** [popekabu/pay_with_paystack#8]
duplicate transaction reference  when you select the momo option. Please help

**Comment by popekabu** [comment]
Please Is your reference unique ?

**Comment by devkumi** [comment]
Yes please, the reference is very unique.

**Comment by devkumi** [comment]
I even used your format for generating the reference. It still return "duplicate references".

**Comment by popekabu** [comment]
Ok, I will check.

**Comment by popekabu** [comment]
I can make you a contributor to the repo if you don’t mind

**Comment by devkumi** [comment]
Alright, that will be a good idea.

**Comment by popekabu** [comment]
Done!
